### ISSUE TITLE
Body text size and justify text

### ISSUE THREAD

**Issue by theevilcat** [anisayari/IMTA-report-latex#1]
Hello Anis,

first, thank you for all the effort to adapt the template to IMT Atlantique format. Is looks beautiful.
I understand that the body text is size 11pt Arial. Is there a way to change this value?

Thank you very much.

**Comment by anisayari** [comment]
All these settings are defined in the class file ```IMTA-report.cls``` . 
The general body size value is given by the line : 
```
\LoadClass[12pt, oneside, a4paper]{report}
````

And the font is defined , for example, here : 

```
\parindent 12pt
\RequirePackage{mathspec}
% use Arno Pro instead of standard LaTeX fonts
\setmathsfont(Digits,Latin,Greek)[
Path = fonts/,Extension = .ttf,
UprightFont=Arial-Regular,
BoldFont=Arial-Bold,
ItalicFont=Arial-Italic,
BoldItalicFont=Arial-BoldItalic,
Numbers={OldStyle,Proportional}]{Arial}
\setmathrm
[Path = fonts/,Extension = .ttf,
UprightFont=Arial-Regular,
BoldFont=Arial-Bold,
ItalicFont=Arial-Italic,
BoldItalicFont=Arial-BoldItalic
]{Arial}

\RequirePackage{xltxtra,xunicode}
\defaultfontfeatures{Mapping=tex-text}
\aliasfontfeatureoption{Ligatures}{Historic}{Historical}
\setromanfont
[Path = fonts/,
Extension = .ttf,
Mapping=tex-text, 
Ligatures={Common}, 
UprightFont=Arial-Regular,
BoldFont=Arial-Bold,
ItalicFont=Arial-Italic,
BoldItalicFont=Arial-BoldItalic
]{Arial} %
```

**Important:** If you wanna add some fonts, make sure that you add them before in the folder `fonts`.

**Comment by theevilcat** [comment]
Thanks a lot for your answer, works great. I was wondering if in that file there is a way to justify the text. The default is to be aligned to the left, but I found no option to change it. You have an idea to change this behavior? Thanks a lot.

**Comment by anisayari** [comment]
Yes I modified the code to justify the text. I'm going to push this enhancement :) .

**Comment by anisayari** [comment]
Pushed in the file `report.tex` with `\justify`
```
% incluude each chapter...
\justify
\include{chapters/chapter1}
\include{chapters/chapter2}
\include{chapters/chapter3}
```

**Comment by theevilcat** [comment]
would this need a modification somewhere else (define the command)?
`Undefined control sequence. \justify` 
Thank you.

**Comment by anisayari** [comment]
@theevilcat  new push to IMTA-report.cls file. Please pull this file. If you get any issues please provide me more details. Thank you.

**Comment by theevilcat** [comment]
Tested it and works great. Thank you very much, you have been very helpful.

**Comment by anisayari** [comment]
You're welcome, thank you for you contribution.
I close the issue. Don't hesitate to open it again or create an other if you still to have problem.
