### ISSUE TITLE
Glossary page

### ISSUE THREAD

**Issue by theevilcat** [anisayari/IMTA-report-latex#2]
Hello,
first: The template is amazing, being using it for my internship report, looks great. Thanks a lot. I was wondering if there is a way to include a glossary page to write the abbreviations and the meaning. Thanks a lot.

**Comment by anisayari** [comment]
I'm not sure to understand. To be clear, could you provide an example how you would like it look ? please

**Comment by theevilcat** [comment]
sure! I uploaded a sample.
Thanks a lot.

[glossary.pdf](https://github.com/anisayari/IMTA-report-latex/files/1198292/glossary.pdf)

**Comment by anisayari** [comment]
Sorry for the delay @theevilcat This features could be an enhancement. Do you want to develop it and contribute ?
There are an easy way to do :  https://en.wikibooks.org/wiki/LaTeX/Glossary

**Comment by theevilcat** [comment]
Hello @anisayari I will take a look at it. Still don't know since I am finishing the internship and preparing the dissertation. I will let you know :)

**Comment by anisayari** [comment]
Start to be solve by @yihongXu here #4

**Comment by anisayari** [comment]
Solved by the pull request #4 , thank you @theevilcat to propose this enhancement and thank you @yihongXU to fix it.

**Comment by theevilcat** [comment]
Thanks a lot, I hope to contribute soon to the project!
